---
name: CI
on:
  pull_request:
    branches:
      - main
  push:

jobs:
  tox:
    uses: daniel-mizsak/workflows/.github/workflows/tox.yml@main
    with:
      python-versions: "['3.11', '3.12']"
      codecov: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
