name: deploy
on:
  workflow_dispatch

jobs:
  deploy:
    if: github.event.workflow_run.event == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
    - name: Remote SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          source ~/virtualenv/PythonVilag/3.8/bin/activate
          python -m pip install --upgrade pip
          cd ~/GitHub
          rm -rf pythonvilag-website
          git clone https://github.com/PythonVilag/pythonvilag-website.git
          cp -r pythonvilag-website/* ~/PythonVilag/
          cd ~/PythonVilag/
          pip install -r requirements.txt
