name: pythonvilag ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Python.
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip.
        run: >
          python -m pip install --upgrade pip

      - name: Install dependencies.
        run: >
          pip install tox tox-gh

      - name: Run tests with tox.
        run: tox
