name: pythonvilag ci
on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Run tests
        env:
          PV_SECRET_KEY: ${{ secrets.PV_SECRET_KEY }}
          FLASK_DEBUG: ${{ secrets.FLASK_DEBUG }}
        run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
    - name: Remote SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          source ~/virtualenv/PythonVilag/3.8/bin/activate
          python -m pip install --upgrade pip
          cd ~/GitHub
          rm -rf pythonvilag-website
          git clone https://github.com/PythonVilag/pythonvilag-website.git
          cp -r pythonvilag-website/* ~/PythonVilag/
          cd ~/PythonVilag/
          pip freeze | xargs pip uninstall -y
          pip install -r requirements.txt
