name: pythonvilag ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh
      - name: Run tests with tox
        run: tox
        env:
          PV_SECRET_KEY: ${{ secrets.PV_SECRET_KEY }}
          FLASK_DEBUG: ${{ secrets.FLASK_DEBUG }}
